name: Trigger auto deployment for redwineapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/redwineapp-AutoDeployTrigger-ccacb8bd-89de-4d2c-9b4c-36534905c7b7.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: agwineacr.azurecr.io
          username: ${{ secrets.REDWINEAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.REDWINEAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: agwineacr.azurecr.io/redwineapp:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.REDWINEAPP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n redwineapp -g winegroup --server agwineacr.azurecr.io --username  ${{ secrets.REDWINEAPP_REGISTRY_USERNAME }} --password ${{ secrets.REDWINEAPP_REGISTRY_PASSWORD }}
            az containerapp update -n redwineapp -g winegroup --image agwineacr.azurecr.io/redwineapp:${{ github.sha }}
